language: python
python:
  - "3.6"      # current default Python on Travis CI
# command to install dependencies
install:
  - pip install -r requirements.txt
# command to run tests
script:
  - python bin/main.py

deploy:
  provider: releases
  api_key: $GITHUB_AUTH_TOKEN
  file: "bin/data.csv"
  skip_cleanup: true
  on:
    tags: false
